# -*- coding: utf-8 -*-
"""Algorithoms_2ndHW_class2_2353881_DaeyeongChoi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12b7z6yIiHJ1XUVuIktmiEIdbyJIezEBp
"""

def max_path_sum_dp(matrix):
    n = len(matrix)
    dp = [[0] * n for _ in range(n)]

    dp[0][0] = matrix[0][0]

    for j in range(1, n):
        dp[0][j] = dp[0][j-1] + matrix[0][j]

    for i in range(1, n):
        dp[i][0] = dp[i-1][0] + matrix[i][0]

    for i in range(1, n):
        for j in range(1, n):
            dp[i][j] = matrix[i][j] + max(dp[i-1][j], dp[i][j-1])

    return dp[n-1][n-1]

matrix = [
    [6, 7, 12, 5],
    [5, 3, 11, 18],
    [7, 17, 3, 3],
    [8, 10, 14, 9]
]

result = max_path_sum_dp(matrix)

print(f"행렬 경로 문제의 동적 프로그래밍 최고값은 {result}입니다.") # 출력 68